### ISSUE TITLE
proposal to decode tuples into structs

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#117]
It seems like the edgedb-go type maping could be improved for tuples. Currently EdgeDB tuples are encoded/decoded to `[]interface{}` in go. This mapping has 2 negative effects.

1. The go driver can't infer the element types of the tuple when the query is prepared.
   This makes it slower to decode tuples because types have to be inferred
	 every time a query executes instead of only when a query is prepared.

2. Users have to do some extra gymnastics in go land to assert the type of each tuple element
   even though the types are defined in the query.

Instead tuples could be mapped to structs the same way that named tuples are:

```go
// named tuple (or object)
type Location struct {
    Lat float64 `edgedb:"lat"`
    Lon float64 `edgedb:"lon"`
}

var result Location
con.QueryOne(ctx, "SELECT (lat := 3.341, lon := 47.0)", &result)


// tuple
type Location struct {
    Lat float64 `edgedb:"0"` // <- use tuple index instead of field name
    Lon float64 `edgedb:"1"`
}

var result Location
con.QueryOne(ctx, "SELECT (3.341, 47.0)", &result)
```

If this approach is adopted it is unclear to me if the same struct should be allowed to have both tuple indexes **and** field names. The edgedb tag is currently used to designate field names for objects and named tuples. If this is adopted what tag syntax should be used?

Option `A` is more concise at the cost of extra string parsing.
```go
type Location struct {
    Lat float64 `edgedb:"lat,0"`
    Lon float64 `edgedb:"lon,1"`
}
```

Option `B` does not require parsing the tag value to check for commas and multiple values but it is much more verbose. Also, the second tuple index specific tag key seems less discoverable.
```go
type Location struct {
    Lat float64 `edgedb:"lat" edgedbindex:"0"`
    Lon float64 `edgedb:"lon" edgedbindex:"1"`
}
```

**Comment by fmoor** [comment]
I'm leaning twoard option `A` because 
- It seems like preparing queries is unlikely to be in the hot path. Query preparation is when the tag values would be parsed. 
- It seems easier to read.
- it seems easier to guess than having a second tag for tuple indexes

**Comment by tailhook** [comment]
Do you need tuple indexes at all? Can you decode into tuple without them (by assuming struct fields equal to tuple fields)? Or is it for complex cases where you need to reorder and skip some fields?

**Comment by fmoor** [comment]
We could decode into untagged struct fields using field order. This seems like it would be unexpected behavior to me though. If someone added a field to a struct that has no tags it could potentially break queries. Or worse not break queries but the data would be marshaled into different struct fields. Also, what would the behavior be for private fields? I don't know of any APIs in go that rely on struct field order. I think I prefer explicitly tagging the index.

**Comment by elprans** [comment]
Like always, we can start with support for explicit tagging and later relax if necessary or desirable.  I think the short syntax is fine.
