### ISSUE TITLE
Unable to run Make test Failing. 

### ISSUE THREAD

**Issue by ShaileshSurya** [edgedb/edgedb-go#129]
Hi, 

I am trying to run the edgedb-go test, but it fails with 

`2021/04/20 05:37:01 EDGEDB_SERVER_BIN not set`

I could not find any documentation on how to set this. Following is the output for the test 

**_~/go_project/src/github.com/ShaileshSurya/edgedb-go# make test
go test -race -timeout=5m ./...
2021/04/20 05:37:01 starting new server
2021/04/20 05:37:01 EDGEDB_SERVER_BIN not set
FAIL    github.com/edgedb/edgedb-go     0.017s
?       github.com/edgedb/edgedb-go/internal/aspect     [no test files]
ok      github.com/edgedb/edgedb-go/internal/buff       (cached)
ok      github.com/edgedb/edgedb-go/internal/cache      (cached)
?       github.com/edgedb/edgedb-go/internal/cardinality        [no test files]
?       github.com/edgedb/edgedb-go/internal/cmd/generr [no test files]
ok      github.com/edgedb/edgedb-go/internal/codecs     (cached)
?       github.com/edgedb/edgedb-go/internal/descriptor [no test files]
ok      github.com/edgedb/edgedb-go/internal/edgedbtypes        (cached)
?       github.com/edgedb/edgedb-go/internal/format     [no test files]
?       github.com/edgedb/edgedb-go/internal/header     [no test files]
ok      github.com/edgedb/edgedb-go/internal/marshal    (cached)
?       github.com/edgedb/edgedb-go/internal/message    [no test files]
?       github.com/edgedb/edgedb-go/internal/soc        [no test files]
FAIL
Makefile:7: recipe for target 'test' failed
make: *** [test] Error 1_**

Go Version:-  **go1.15.11 linux/amd64**

Also, I am running my edgedb-dev server on a remote machine. Will there be tinkering needed on the test to consume calls to the server?

**Comment by fmoor** [comment]
@ShaileshSurya thanks for the feedback! The test suite assumes that edgedb server is installed locally. The testsuite starts a new edgedb server instance that destroys itself when the test suite finishes (the last client disconnects). 

Once you have [installed a server locally](https://www.edgedb.com/docs/tutorial/install/) there should be a command in your shell `$PATH` called `edgedb-server-1-beta1-c23b7a1`. The `1-beta1-c23b7a1` part of the name may be different depending on what version you install. The server command name is the expected value for `EDGEDB_SERVER_BIN`

```bash
$ EDGEDB_SERVER_BIN=edgedb-server-1-beta1-c23b7a1 make test
```

The test suite is expected to pass under both the latest stable edgedb version (`edgedb server install`) as well as the latest nightly build (`edgedb server install --nightly`).

**Comment by ShaileshSurya** [comment]
Hi @fmoor 

Thank you for getting back. 

I could not find the `edgedb-server-1-beta1-c23b7a1` in the path variable, but I could find the edgedb-server executables at path on the `/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/bin` for ubuntu and `/usr/bin/edgedb-server-1-beta1 -> /usr/lib64/edgedb-server-1-beta1/bin/edgedb-server*` for centos, but unfortunately I could not find the same on the windows. I checked the Path variable of windows too. 

I am using windows as my development box, thus trying to run the test cases on windows. 

Do we know where can this be found on the windows?

**Comment by fmoor** [comment]
On linux if the command `which edgedb-server-1-beta1-c23b7a1` prints a path then you could use command I listed above. If `which edgedb-server-1-beta1-c23b7a1` doesn't print anything then you could use this:
```bash
$ EDGEDB_SERVER_BIN=/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/bin/edgedb-server-1-beta1-c23b7a1 make test
```
`edgedb-server` currently doesn't work natively on windows. It runs in docker on windows. So, I don't think there is a nice way to make the test suite run on windows.

**Comment by ShaileshSurya** [comment]
Hi @fmoor ,

Thank you. This helps. By the way, thank you for such awesome work. 

I am trying to build a java-binding of edgedb. https://github.com/ShaileshSurya/edgedb-java

I was pointed out by Yuri to have look at how you have written the CI pipeline and the proper end-to-end tests. I have a good familiarity with GoLang and will take much of the inspiration from your driver. 

Since you have already walked the path for GoLang binding, I could use your expertise for the java binding. It will be really great if we could connect offline over email. 

Regards, 
Shailesh S.
ss.shailesh28@gmail.com

**Comment by fmoor** [comment]
I'd be happy to try and answer questions about EdgeDB drivers. Perhaps it is better to have the conversation in the open so that others who are also interested in building drivers could learn from our conversation? Feel free to post questions in this issue or mention me in a new [disscussion](https://github.com/edgedb/edgedb/discussions).

**Comment by ShaileshSurya** [comment]
Thank you @fmoor. This helps. We can close this issue for now.
