### ISSUE TITLE
require nullable values for missing fields

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#135]
Currently unset properties are skipped when decoding to structs in go leaving whatever value was there before the call to `Query()`. The driver should require the out type to implement some sort of nullable interface or return an error when this happens.

**Comment by fmoor** [comment]
@1st1 How does the client know if a property is required or not based on an object type descriptor? The only flags I see are related to implicit properties and links. https://www.edgedb.com/docs/internals/protocol/typedesc#object-shape-descriptor Are there undocumented flags?

**Comment by 1st1** [comment]
Hm, you're right. I was 100% sure we have that info. Perhaps we should add it, and while there, bump the flags field to int32. @elprans ?
