### ISSUE TITLE
How to INSERT optional type values?

### ISSUE THREAD

**Issue by divan** [edgedb/edgedb-go#151]
So I'm trying to adapt the code to the new changes in 0.8.0, and can't find a way to INSERT optional values.

Given the schema:
```esdl
module default {
    type Test {
		property name -> str;
    }
};
```

And code
```go
package main

import (
	"context"
	"log"

	"github.com/edgedb/edgedb-go"
)

func main() {
	opts := edgedb.Options{}
	ctx := context.Background()
	pool, err := edgedb.Connect(ctx, opts)
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close()

	var name edgedb.OptionalStr
	name.Unset()

	var id struct{ id edgedb.UUID }
	err = pool.QuerySingle(ctx, `INSERT Test {
		name := <str>$0,
	}`, &id, name)
	if err != nil {
		log.Fatal(err)
	}
}
```

I get an error `edgedb.InvalidArgumentError: cannot encode edgedb.OptionalStr at args[0] because its value is missing`. Which sounds both logical (the whole point of `OptionalStr` type is to distinguish missing values, right?) and confusing. Like, yes value is missing and that's exactly what I want to store in database. I.e. for this particlar record, field `name` is missing. (Thinking in usual SQL terms, I want to set it to "NULL" rather than empty string).

How do I do it with current API?

**Comment by fmoor** [comment]
With the current API the query needs to be `INSERT Test;` with the name property omitted.

**Comment by elprans** [comment]
An `OPTIONAL` modifier to the argument should work too:

```
err = pool.QuerySingle(ctx, `INSERT Test {
    name := <OPTIONAL str>$0,
}`, &id, name)
```

**Comment by divan** [comment]
@elprans wow, how did I miss that in the docs! Thank you!

**Comment by divan** [comment]
> With the current API the query needs to be `INSERT Test;` with the name property omitted.

Right, but in more real-life code there will be plenty of fields, some of them required and some are optional

**Comment by divan** [comment]
> An `OPTIONAL` modifier to the argument should work too:

Weird, I'm still receiving the same error.

I'm using today's nightly server version and edgedb-go 0.8.0.

```go
package main

import (
	"context"
	"log"

	"github.com/edgedb/edgedb-go"
)

func main() {
	opts := edgedb.Options{}
	ctx := context.Background()
	pool, err := edgedb.Connect(ctx, opts)
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close()

	var name edgedb.OptionalStr
	name.Unset()

	var id struct{ id edgedb.UUID }
	err = pool.QuerySingle(ctx, `INSERT Test {
		name := <OPTIONAL str>$0,
	}`, &id, name)
	if err != nil {
		log.Fatal(err)
	}
}
```

```bash
go run main.go
2021/08/16 20:17:10 edgedb.InvalidArgumentError: cannot encode edgedb.OptionalStr at args[0] because its value is missing
exit status 1
```

**Comment by fmoor** [comment]
> Right, but in more real-life code there will be plenty of fields, some of them required and some are optional

Sure. Using `OPTIONAL` or omitting the field depends on the use case. If the query will sometimes insert an optional field then `OPTIONAL` is probably the way to go. If a query will never insert a field then omitting the field is probably more clear.

```
module default {
    type Test {
        property first -> str;
        property second -> str;
    }
};
```

```go
err = pool.QuerySingle(ctx, `INSERT Test {
    second := <str>$0,  # the first field is omitted
}`, &id, "some second field val")
```

**Comment by fmoor** [comment]
> 2021/08/16 20:17:10 edgedb.InvalidArgumentError: cannot encode edgedb.OptionalStr at args[0] because its value is missing

I didn't know about the `OPTIONAL` syntax when I added this feature. This is a bug. I'll work on this today. Thanks @divan!

**Comment by divan** [comment]
> If the query will sometimes insert an optional field then `OPTIONAL` is probably the way to go.

Right, but in real-life code that means hand-crafting EdgeQL query using string concatenation, based on the `IsSet` status of the Optional- variable, right? Doesn't look too enticing. :)

**Comment by fmoor** [comment]
> in real-life code that means hand-crafting EdgeQL query using string concatenation, based on the IsSet status of the Optional- variable, right?

I don't think so. [Your example](https://github.com/edgedb/edgedb-go/issues/151#issuecomment-899679722) is supposed to work. That it complains about the argument value being missing is not the correct behavior.

```
INSERT Test {
    name := <OPTIONAL str>$0,
}
```

This query should be valid if `$0` is missing and if it is present. I'll work on a fix for this.

**Comment by divan** [comment]
Right, but your suggested alternative to OPTIONAL was omitting the field, and I wondering how do I do it in an example such as this one:

```go
type Person struct {
    ID        edgedb.UUID              `edgedb:"id"`
    Name      edgedb.OptionalStr       `edgedb:"name"`
    Surname   edgedb.OptionalStr       `edgedb:"surname"`
    Fullname  edgedb.OptionalStr       `edgedb:"fullname"`
    Gender    edgedb.OptionalStr       `edgedb:"gender"`
    BirthDate edgedb.OptionalLocalDate `edgedb:"birth_date"`
    DeathDate edgedb.OptionalLocalDate `edgedb:"death_date"`
    Bio       edgedb.OptionalStr       `edgedb:"bio"`
    Slug      edgedb.OptionalStr       `edgedb:"slug"`
}

func insertPerson(p Person) error {
    var id struct{ id edgedb.UUID }
    _ := db.QueryOne(ctx, `INSERT Person {
            name := <str>$0,
            surname := <str>$1,
            gender := <str>$2,
            birth_date := <cal::local_date>$3,
            death_date := <cal::local_date>$4,
            bio := <str>$5,
            slug := <str>$6,
        }`, &id,
        person.Name,
        person.Surname,
        person.Gender,
        person.BirthDate,
        person.DeathDate,
        person.Bio,
        person.Slug)
    //...
    return nil
}
```

**Comment by fmoor** [comment]
> I wonder how do I do it in an example such as this one

It seems in that scenario any property mentioned in the query may have a value so `OPTIONAL` would be the way to go :+1:

**Comment by fmoor** [comment]
**Status update**: it seems that a change is needed in both the server and the go language bindings to make `OPTIONAL` work correctly so this will take a little longer to fix than I initially had hoped.

**Comment by divan** [comment]
@fmoor do you have any ETA on fixing it?
I need to decide if I should switch back to beta-2 or wait a little bit, as this issue is a stopper for a project.

**Comment by fmoor** [comment]
@divan I would guess that a fix for this will land in nightly for the server some time next week or perhaps the week after. A fix for the go bindings should be available a few days after that worst case.

**Comment by divan** [comment]
Got it. Thanks for the update @fmoor!

**Comment by divan** [comment]
Just wondering if there is any progress with this issue?

This problem with optional types and beta1.3 is a showstopper to me. I don't want to write a lot of new code for beta1.2 (i.e. without optional types), knowing that I'll have rewrite a great share of it later for 1.3. But with 1.3 and optional types there is no sane way to insert optional values at all.

**Comment by fmoor** [comment]
@divan thanks for checking in! The changes to the server are in place now and I am working on the changes for `edgedb-go`. The internal changes to `edgedb-go` are a bit more significant than I originally guessed, but I hope to have a PR up sometime this week :crossed_fingers: Fixing this is a top priority.

**Comment by fmoor** [comment]
@divan was just released `github.com/edgedb/edgedb-go@v0.8.2` and should support OPTIONAL types correctly.

**Comment by divan** [comment]
@fmoor Fantastic, thank you! I'll be testing it over the weekend.

**Comment by divan** [comment]
@fmoor I'm trying the latest updates for both server and edgedb-go, and still getting the same error.

Here is the code for test:

```go
package main

import (
	"context"
	"log"

	"github.com/edgedb/edgedb-go"
)

func main() {
	opts := edgedb.Options{}
	ctx := context.Background()
	pool, err := edgedb.Connect(ctx, opts)
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close()

	var name edgedb.OptionalStr
	name.Unset()

	var date edgedb.OptionalLocalDate
	date.Unset()

	var id struct{ id edgedb.UUID }
	err = pool.QuerySingle(ctx, `INSERT Test {
		name := <OPTIONAL str>$0,
		date := <OPTIONAL cal::local_date>$1,
	}`, &id, name, date)
	if err != nil {
		log.Fatal(err)
	}
}
```

go.mod:

```
module test

go 1.16

require github.com/edgedb/edgedb-go v0.8.2
```

edgedb instance is created with nightly server.

`go run main.go` yields this error:
```
2021/09/20 12:41:22 edgedb.InvalidArgumentError: cannot encode edgedb.OptionalStr at args[0] because its value is missing
exit status 1
```

I'm I missing something?

**Comment by fmoor** [comment]
@divan have you upgraded your edgedb server to a recent nightly? `edgedb project upgrade --to-nightly` should do the trick.

What is the result of this query? `SELECT sys::get_version_as_str();`

**Comment by divan** [comment]
@fmoor yes, I tried both upgrading and recreating with `--server-version nightly` flag.

```
$ edgedb
EdgeDB 1.0-beta.4+dev5900.d2021081600.g7e72cf894.cv202108020000 (repl 1.0.0-beta.3)
Type \help for help, \quit to quit.
edgedb> SELECT sys::get_version_as_str();
{'1.0-beta.4+dev5900.d2021081600.g7e72cf894.cv202108020000'}
edgedb>
```

**Comment by fmoor** [comment]
@divan `1.0-beta.4+dev5900.d2021081600.g7e72cf894.cv202108020000` is an out of date version of nightly. I believe the most recent one is `1.0-beta.4+dev5966.d2021091116.ge53d0566c.cv202109030000`. I _think_ `edgedb instance upgrade --local-minor` will upgrade the nightly version to the latest nightly. I'm not an expert with the CLI so I'm learning with you here.

**Comment by divan** [comment]
Thanks, but still no luck:

```
$ edgedb project upgrade --to-version "1.0-beta.4+dev5966.d2021091116.ge53d0566c.cv202109030000"
edgedb error: Unable to determine version: Version 1.0-beta.4+dev5966.d2021091116.ge53d0566c.cv202109030000 not found
```

How one finds the version for the latest nightly build?

Datetime string in nightly version definitely looks wrong (20210802). Looks like a bug with `upgrade`, no?

**Comment by tailhook** [comment]
`edgedb project upgrade` should do the upgrade.

_`--to-nightly` switches the "upgrade channel" so it only changes the actual version when stable was used. `--local-minor` doesn't touch nightlies. And `--to-version` only switches to major version, i.e. `1-beta3` not exact version._

**Comment by tailhook** [comment]
> Datetime string in nightly version definitely looks wrong (20210802). Looks like a bug with upgrade, no?

`cv202108020000` is not an actual version number or a date, it's a timestamp of the schema update (which you should sync of as a version of some essential dependency of the server, but not the server itself). `.d2021091116` part is the actual build date. And I think this is the latest one at the moment.

**Comment by divan** [comment]
@fmoor any ideas where to go from here? Is it something with my version of nightly or the issue is still there.

On a side note, another question related to inserting optional values – this time optional links.

For required links I use the following code (assuming `author` is required and selected from the existing ones):

```
INSERT Book {
...
            author := (
                SELECT User
                FILTER .id = <uuid>$0
                LIMIT 1),
...
```

but if `author` field is optional, how do I insert it? I tried to use coalescing operator (??) but don't know how to tell that "there is no value" so it properly handled in case of optional link. Any advice here?
Thank you!

**Comment by fmoor** [comment]
> Is it something with my version of nightly or the issue is still there.

If your version of nightly is not the latest (`d2021091116`) then it needs to be upgraded. Did you try `edgedb project upgrade` like @tailhook suggested? 

> if `author` field is optional, how do I insert it?

Are you wanting to insert an author if a particular parameter is provided to the query and have no author at all if the parameter is missing?

**Comment by tailhook** [comment]
> If your version of nightly is not the latest (d2021091116) then it needs to be upgraded. Did you try edgedb project upgrade like @tailhook suggested?

This one is the latest for now, but we should have nightly builds fixed today. So tomorrow you should be able to upgrade to the more fresh one.

**Comment by divan** [comment]
> Are you wanting to insert an author if a particular parameter is provided to the query and have no author at all if the parameter is missing?

Correct. I read in docs that "everything is a set" in EdgeDB, but when it comes to optional values, I'm still thinking in terms of "NULL" (value or nothing). So basically I want to use the same insert query for optional values (including optional links). If value is not missing, then it should be inserted, if it's missing – there should be "null"/"nothing". And I struggle to understand how to implement this with optional links.

> Did you try `edgedb project upgrade` like @tailhook suggested?

Yes.

> So tomorrow you should be able to upgrade to the more fresh one.

Thank you. Trying it now.

**Comment by divan** [comment]
After upgrading to nightly it seems to finally work. Great job, thank you!

Still an open question about inserting optional links. Should I move to Discussions section maybe?

**Comment by fmoor** [comment]
> Should I move to Discussions section maybe?

I think this is a good idea. If you would add a link here to the new discussion that would be helpful!

**Comment by tailhook** [comment]
You can also drop `LIMIT 1` on that query, as EdgeDB is smart enough to know that only one object is always returned.

**Comment by divan** [comment]
@tailhook thanks you so much. Going to try this now. To be honest, though, I doubt I ever remember this query, so will have to save it as a snippet somewhere. I wish inserting optional values were as simple as inserting required values: just write the query, and let EdgeDB figure out that "nothing should be inserted if value is missing" for optional value.

**Comment by elprans** [comment]
@divan, if you don't care about the scenario where the linked object id is present, but invalid, then the query becomes a lot simpler:

```
    author := (SELECT User FILTER .id = <OPTIONAL uuid>$0)
```

This works because an empty `$0` id would not match any users and the query would return an empty set as a result.
