### ISSUE TITLE
Pooling implementation

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#19]
per https://github.com/edgedb/edgedb-go/pull/1#discussion_r519968141

## Pool Configuration
Pool configuration is fixed after creation.
- `MaxConns`, default = `max(4, runtime.NumCPU())`
- `MinConns`, default = 1

## Functions
```go
func Connect(context.Context, Options) (*Pool, error)

// ignores pool specific configuration
func ConnectOne(context.Context, Options) (*Conn, error)
```

## Pool API
```go
type Pool struct {
    func (*Pool) Execute(context.Context, string) error
    func (*Pool) Query(context.Context, string, interface{}, ...interface{}) error
    func (*Pool) QueryOne(context.Context, string, interface{}, ...interface{}) error
    func (*Pool) QueryJSON(context.Context, string, *[]byte, ...interface{}) error
    func (*Pool) QueryOneJSON(context.Context, string, *[]byte, ...interface{}) error
    func (*Pool) Acquire(context.Context) (*PoolConn, err)

    // Close closes all connections blocking until acquired connections are released.
    func (*Pool) Close() error
}
```

## Conn API
```go
type baseConn struct {
    func (*Conn) Execute(context.Context, string) error
    func (*Conn) Query(context.Context, string, interface{}, ...interface{}) error
    func (*Conn) QueryOne(context.Context, string, interface{}, ...interface{}) error
    func (*Conn) QueryJSON(context.Context, string, *[]byte, ...interface{}) error
    func (*Conn) QueryOneJSON(context.Context, string, *[]byte, ...interface{}) error
}

type Conn struct {
    Conn // i.e. has all the methods Conn does
    func (*Conn) Close() error
}

type PoolConn struct {
    Conn // i.e. has all the methods Conn does

    // Release puts the connection back in the Pool.
    // After the first call to Release() all methods on PoolConn will panic when called.
    func (*PoolConn) Release()
}
```

**Comment by fmoor** [comment]
@1st1 let me know if I missed anything important here.

**Comment by 1st1** [comment]
> MinConns, default = 0

What does this mean? Ideally, when you create the pool, it should establish at least one connection (to verify connection params etc).

> MaxConnIdleTime and MaxConnLifeTime

We'll actually have these tuneable at the DB level (on the server side). Having them on the client side is great, but maybe we'll need to make sure that it's not possible to set up `MaxConnIdleTime` to be longer on the client than it is configured on the server. cc @tailhook and @elprans 

Ultimately we need to make our connection/pooling API to match conceptually other popular and builtin drivers.

**Comment by fmoor** [comment]
>> MinConns, default = 0
>
> What does this mean? Ideally, when you create the pool, it should establish at least one connection (to verify connection params etc).

That is the default for pgx. I can make it 1 though :+1:

**Comment by fmoor** [comment]
@1st1 should I leave out the connection idle and life time for now?

**Comment by 1st1** [comment]
> @1st1 should I leave out the connection idle and life time for now?

Yeah, let's implement them in a 2nd stage and in the meantime have an opportunity to discuss them.

**Comment by tailhook** [comment]
For idle time, the idea was that server announces idle timeout: https://github.com/edgedb/edgedb/discussions/1914

I also don't think `MaxConnLifeTime` makes any sense. While traditionally databases were used the setting to avoid memory leak (or memory fragmentation). I think edgedb's async internal design makes that ineffective (even if we want to recycle postgres connections after some time that's a job of edgedb connection pool, not client's).

**Comment by fmoor** [comment]
Should the user be able to get access to a single connection (excluding some transaction API)? Should something like this be allowed?

```go
conn := pool.Conn()
defer conn.Return()  // returns conn to pool
conn.Query()
conn.Query()

```

**Comment by 1st1** [comment]
> Should the user be able to get access to a single connection (excluding some transaction API)? Should something like this be allowed?

Do other Go DB drivers allow that?

**Comment by fmoor** [comment]
Yes they all do database/sql, github.com/lib/pq, github.com/jackc/pgx & github.com/go-pg/pg. I'm not sure what the reason is though and if it extends to edgedb :thinking:

**Comment by fmoor** [comment]
Then the follow on question is, if access to a conn object is allowed do you allow opening/connecting a conn directly outside of a pool? github.com/jackc/pgx allows this but it is the only one.

**Comment by 1st1** [comment]
> Yes they all do database/sql, github.com/lib/pq, github.com/jackc/pgx & github.com/go-pg/pg. I'm not sure what the reason is though and if it extends to edgedb

The reason for that is to constrain your code to one physical connection to the DB. That might help you to keep track of transaction state etc. Since other drivers (including the standard ones) allow this, and we allow this in our other clients, let's allow that in Go too.

**Comment by fmoor** [comment]
Updated the description with a proposed API for pools. cc @1st1

**Comment by 1st1** [comment]
* I think `QueryOneJSON` and `QueryJSON` should return a tuple of `[]byte, error`

* `ConnectConn` -- is it similarly called in other drivers? I'd call it `ConnectOne`.

* `func (*Pool) Conn(context.Context) (*PoolConn, err)` is this how it's called in other drivers? In our Python implementation we call it `acquire/release`

*  `// Close closes the underlying net.Conn and removes the conn from the pool.` -- I don't think it should have the 'Close' method. The removal of a connection from the pool should be a concern at the level where the pool was created, imo.

**Comment by fmoor** [comment]
- > I think QueryOneJSON and QueryJSON should return a tuple of []byte, error

  The reason that these use an out parameter is so that they don't have to allocate memory and the user can reuse memory if  they want. Let me know if this doesn't seem worth while. 

- > ConnectConn -- is it similarly called in other drivers? I'd call it ConnectOne.

  The only driver that allows this is pgx and it uses 2 packages `pgx.Connect` & `pgxpool.Connect`. `ConnectOne` is fine with me :+1: 

- > func (*Pool) Conn(context.Context) (*PoolConn, err) is this how it's called in other drivers? In our Python implementation we call it acquire/release

  This is the name in database/sql. pgx calls it Acquire/Release. I'll change it to match other edgedb clients.

- > // Close closes the underlying net.Conn and removes the conn from the pool. -- I don't think it should have the 'Close' method. The removal of a connection from the pool should be a concern at the level where the pool was created, imo.

  Ok. I'll change this.

**Comment by fmoor** [comment]
When `Pool.Acquire()` or any of the `Pool.QueryX()` methods is called and there is an error connecting a new socket to the server I'm planing to return the connection error. The user is allowed to make subsequent calls to `Acquire()` and it is up to them to close the Pool if it never connects again.

Let me know if there is a better way.
