### ISSUE TITLE
Query pass slice

### ISSUE THREAD

**Issue by MainTobias** [edgedb/edgedb-go#228]
I have yet to find a way to pass a slice of edgedb.UUIDs to *edgedb.Client.Query.

**Comment by MainTobias** [comment]
```
err = db.QuerySingle(ctx, `
        INSERT Restaurant {
            owner := <User>(Select User filter .id = <uuid>$0),
            managers := <User>(Select User filter .id = <uuid>$1),
	    name := <str>$2,
	    description := <str>$3
        }
    	`, &c, randomUser(db, insertedUsers).ID,
			randomUserIDs(db, insertedUsers, 3),
			gofakeit.Company(),
			gofakeit.Adverb())
```

**Comment by fmoor** [comment]
Am I reading this correctly? It looks like you want to pas several `User` ids to `$1` to select multiple managers? Passing sets as arguments is not supported so you need to change the query to make `<uuid>$1` an array. I think something like this will work for the managers sub query.

```
select User filter contains(<array<uuid>>$1, .id)
```

This might be an alternative spelling.

```
select User filter .id in array_unpack(<array<uuid>>$1)
```

**Comment by MainTobias** [comment]
Thank you maybe there is a way to include that in the docs? I believe it might be helpful for new users.

**Comment by fmoor** [comment]
I'll have a look at adding it.

**Comment by fmoor** [comment]
added this to the docs in https://github.com/edgedb/edgedb-go/commit/7315ffdbf20cbff04b02f9a19db845e8cd42a4fe
