### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#24]
Careful consideration should be given to all returned errors and panic values. 

## References
https://go.googlesource.com/proposal/+/master/design/go2draft.md
https://pkg.go.dev/github.com/spacemonkeygo/errors
https://github.com/juju/errgo
https://pkg.go.dev/github.com/hashicorp/errwrap
https://pkg.go.dev/github.com/pkg/errors

**Comment by 1st1** [comment]
Yes, at least for the next couple of months until we implement https://github.com/edgedb/edgedb/discussions/1849 ;)

**Comment by fmoor** [comment]
:question: What error type should checks that ought never fail return? (noting this here so I don't forget when I get around to implementing)
