### ISSUE TITLE
edgedb.Duration and time.Duration operate on different scales

### ISSUE THREAD

**Issue by joeyak** [edgedb/edgedb-go#248]
The `edgedb.Duration` type is a microsecond count

```go
// Duration represents the elapsed time between two instants
// as an int64 microsecond count.
type Duration int64
```

meanwhile the standard library `time.Duration` is a nanosecond count

```go
// A Duration represents the elapsed time between two instants
// as an int64 nanosecond count. The representation limits the
// largest representable duration to approximately 290 years.
type Duration int64
```

I noticed this while running the code below with duration being `time.Second * 15`

```go
err = w.db.Execute(context.Background(), `
	INSERT WatchTime {
		watch_duration := <duration>$0,
		user := (SELECT User FILTER .name = <str>$1),
		channel := (SELECT User FILTER .external_id = <str>$2)
	}
`, edgedb.Duration(duration), user, channel)
```

This results in a 4 hour and 10 minute duration
![image](https://user-images.githubusercontent.com/27922090/206636173-bf5ce5d8-5bfd-43f3-9fd2-8c2df57fee91.png)

after updating the code to `edgedb.Duration(duration/time.Microsecond)` the time shows correctly
![image](https://user-images.githubusercontent.com/27922090/206636393-5d449d9f-5801-44ef-9f2f-a78b977e2cd2.png)

I also was able to get my code to work properly with `time.Duration(watchTime.Duration)*time.Microsecond` for going from edgedb to time

Is this the suggested way to handle the time conversion, or is this considered a bug?

**Comment by fmoor** [comment]
> Is this the suggested way to handle the time conversion, or is this considered a bug?

This is a simple way to handle the conversion and it may be fine for some use cases but it is not correct in the general case because it doesn't detect overflows. Go's `time.Duration` can only go up to about 290 years, but `edgedb.Duration` can be much larger than that so to be correct the conversion should probably return an error if `time.Duration` can't represent the `edgedb.Duration`.

**Comment by joeyak** [comment]
Are we supposed to be able to put `time.Duration` in the model to parse? I think I originally started using `edgedb.Duration` because I got an error on `client.Query()`.

On the [docs](https://www.edgedb.com/docs/clients/go/index) it mentions time.Duration as being a possible conversion, but maybe that was just a type?
![image](https://user-images.githubusercontent.com/27922090/206767654-916b7cd5-9b36-4954-8209-14d4c6dc8ee3.png)

below is the object

```go
type WatchTime struct {
	edgedb.Optional
	ID        edgedb.UUID   `edgedb:"id" json:"id"`
	Duration  time.Duration `edgedb:"watch_duration" json:"watch_duration"`
	CreatedAt time.Time     `edgedb:"created_at" json:"created_at"`
}
```

and the error returned

> error logging watchers for 46198525: could not log users watching: could not get watchtimes for 46198525: edgedb.InvalidArgumentError: the "out" argument does not match query schema: expected struct { Key struct { User database.User "edgedb:\"user\""; Channel database.User "edgedb:\"channel\"" } "edgedb:\"key\""; Info database.WatchTime "edgedb:\"info\"" }.info.watch_duration to be edgedb.Duration or edgedb.OptionalDuration got time.Duration

**Comment by fmoor** [comment]
Good catch! That is a typo. It should be `edgedb.Duration`.
