### ISSUE TITLE
Document if the Client can be useed concurrently.

### ISSUE THREAD

**Issue by chirino** [edgedb/edgedb-go#311]
**Describe the bug**

It's not clear if the Client can be used concurrently.  Should we be creating a new client for each http request serviced, or is it safe to share one across all requests?

**Comment by fmoor** [comment]
The documentation for the [Client type](https://pkg.go.dev/github.com/edgedb/edgedb-go#Client) says:

> Client is a connection pool and is safe for concurrent use. 

Where do you recommend putting further documentation about this?

**Comment by chirino** [comment]
Missed that.  Thanks!
