### ISSUE TITLE
argument types that don't match query should return error instead of panic

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#33]
Currently this panics on the type assertion for  `1` & `1111`

```go
var res []interface{}
ctx := context.Background()
err := conn.QueryOne(ctx, "SELECT (<int16>$0 + <int16>$1,)", &res, 1, 1111)
```

**Comment by fmoor** [comment]
This seems to have been fixed in https://github.com/edgedb/edgedb-go/pull/51

**Comment by fmoor** [comment]
I spoke too soon...

**Comment by 1st1** [comment]
> I spoke too soon...

You saw it happening again?

**Comment by fmoor** [comment]
> You saw it happening again?

sorry, I'm conflating two issues. The bug outlined in the description is fixed. There is another one fixed in https://github.com/edgedb/edgedb-go/pull/53 that I erroneously reopened this for.
