### ISSUE TITLE
add support for custom scalars

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#45]
There is not a codec yet for the [scalar type descriptor](https://www.edgedb.com/docs/internals/protocol/typedesc#scalar-type-descriptor). The driver should handle descriptor type 3.

**Comment by 1st1** [comment]
Not sure I understand what this issue is about.

**Comment by fmoor** [comment]
> Not sure I understand what this issue is about.
I updated the description.

**Comment by 1st1** [comment]
> There is not a codec yet for the scalar type descriptor. The driver should handle descriptor type 3.

The link links this very issue. You probably wanted to link the docs?

> I updated the description.

Still not clear. Perhaps you meant "add support for custom scalars", e.g. when I have a type like `scalar type my_int extending int64`, right?

**Comment by fmoor** [comment]
> The link links this very issue.

Oops... :facepalm: 

> You probably wanted to link the docs?

Correct. Updated.
