### ISSUE TITLE
implement decimal codec

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#47]

**Comment by fmoor** [comment]
I'm not sure what the right go type is for this codec. The options seems to be:

1. [big.Rat](https://golang.org/pkg/math/big/#Rat) (not fixed-point decimal precision)
2. [big.Float](https://golang.org/pkg/math/big/#Float) (not fixed-point decimal precision)
3. [github.com/shopspring/decimal](https://github.com/shopspring/decimal) (3rd party) - seems to be maintained and widely used, but has [limitations](https://github.com/shopspring/decimal/issues/207).
4. [github.com/cockroachdb/apd](https://github.com/cockroachdb/apd/v2) (3rd party) - maintained, full featured, more performant than `3`
5. Our own type that knows how to convert it's value to some or all of the above?

We can support more than one target type so the options are not mutually exclusive.

**Comment by 1st1** [comment]
I don't want us to bundle or adapt to some specific 3rd party library. Ideally we need to figure out an API that would allow users to plug their library of choice. Take a look at how asyncpg handles custom codecs. Go is of course a different beast, but maybe we can come up with a good solution.

**Comment by fmoor** [comment]
I think something similar to go's [marshaler interfaces](https://golang.org/pkg/encoding/#BinaryMarshaler) would work well for this. This interface would only be used for EdgeDB scalar values excluding arrays.

```go
package edgedb

type Marshaler interface  {
    MarshalEdgeDB() ([]byte, error)
}

type Unmarshaler interface {
    UnmarshalEdgeDB([]byte) error
}
```

Instead of registering a codec for the edgedb type, go values that implement the interface will marshal themselves. This has a few advantages.

1. this pattern is familiar to go developers
2. you don't have to configure the client with special codecs

**Comment by 4thel00z** [comment]
Greetings @1st1 I am not sure why there is this DIY approach, if there is proper stdlib primitive that can be used as sensible defaults. Decimal is usually used for prices which are floats.
This is probably like 90% of all use cases. Can big.Rat (no pun intended) be used as default ?
Happy to contribute a PR in case of a yes.

**Comment by fmoor** [comment]
> Can big.Rat (no pun intended) be used as default?

The problem with using `big.Rat` is that it is not a fixed point decimal precision type, but EdgeDB's `std::decimal` type is. This means that 1) there is not a nice conversion between the two types 2) math done using EdgeDB's decimal type may not produce the same results as math done using `big.Rat`. For money it is usually better to store the value as cents or tenths of cents using `std::int64`.

**Comment by 4thel00z** [comment]
- big.Rat != std::decimal in calculations -> understood
- money **storing** is better done in `std::int64` -> this argument is seen from db impl. perspective and I understand the tradeoff consideration; but going down that route would mean there seems to be a semi-best practice that the "money" math should be done in edgedb (?)

Am I following the reasoning properly ? @fmoor  
Thanks for your time btw. 👍🏽
