### ISSUE TITLE
documentaion review

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#64]
- The documentation needs to be reviewed for completeness. 
- All `...` should be replaced with meaningful descriptions. 
- Examples should be added where appropriate.

**Comment by fmoor** [comment]
After adding all the auto generated errors the godoc output is almost unusable. It is quite difficult to find anything or determine what is important in the enormous list of error names (see first image). It seems much more useful with all the errors removed (see second image). If the error types were moved to a separate package godoc would put the errors on their own page. I'm not sure if this is a good idea since the API is probably nicer to use with only one package. @1st1 what do you think?

![image](https://user-images.githubusercontent.com/8278635/104962823-79e5c580-5996-11eb-912a-f107e70d8487.png)

![image](https://user-images.githubusercontent.com/8278635/104963109-0a240a80-5997-11eb-9ced-402da0ab6f9f.png)

**Comment by 1st1** [comment]
Ю I'm not sure if this is a good idea since the API is probably nicer to use with only one package. @1st1 what do you think?

I think it's a good idea. Do you have any good example of how the separate package for errors would make code look worse?  We can probably keep the root `Error` (which should be called `EdgeDBError`, no?) type in the main package.

**Comment by fmoor** [comment]
> the root Error (which should be called EdgeDBError, no?)

I don't think so. In go you must always use the package name when referring to imported identifiers, so this will always be `edgedb.Error`.

**Comment by fmoor** [comment]
> Do you have any good example of how the separate package for errors would make code look worse?

In go you can't nest package names like this `edgedb.errors.SomeError` you can only write something like `errors.SomeError` so I'm not sure what the package should be called. There are already several prominent packages called `errors` and `error` is a built in type name. Maybe `edberr` or `edgedberr`. `edgedberr` feels long to me especially considering how long most of the error names are already. Some other name... My hesitation in breaking out a separate error package is only because `edgedb.SomeError` seems like the nicest name.

**Comment by fmoor** [comment]
> We can probably keep the root Error type in the main package.

We could but why is it special? Keeping it in the main package might make be misleading for someone that is just skimming the documentation. It would look like there is only one error type. It seems better to me to keep all error types and `ErrorTag` in the same package whichever that ends up being.

**Comment by 1st1** [comment]
> We could but why is it special? Keeping it in the main package might be misleading for someone that is just skimming the documentation. It would look like there is only one error type. It seems better to me to keep all error types and ErrorTag in the same package whichever that ends up being.

The use case I have in mind for keeping just the `Error` type in the `edgedb` package is that I believe most people won't check what specific error the API has returned. Basically, I imagine that a common use case would be to check if it's an EdgeDB-related error or something else. Also checking for specific errors is a somewhat advanced pattern. We can also document that there are more error types in the docs of `edgedb.Error`.

**Comment by 1st1** [comment]
> In go you can't nest package names like this edgedb.errors.SomeError you can only write something like errors.SomeError so I'm not sure what the package should be called. There are already several prominent packages called errors and error is a built in type name. Maybe edberr or edgedberr. edgedberr feels long to me especially considering how long most of the error names are already. Some other name... My hesitation in breaking out a separate error package is only because edgedb.SomeError seems like the nicest name.

As for naming -- I'd go with `edgedberr`. IMO it's nice and predictable for the user when related packages are prefixed with the name of the main package.

**Comment by elprans** [comment]
Is the plan to use godoc to publish the docs, or are we going to parse/integrate into the main docs like we do with Sphinx?  If it's the latter, then I think we can separate errors at the rendering stage, no?  IMO, the suckiness of the tool shouldn't be informing the package structure.

**Comment by 1st1** [comment]
> Is the plan to use godoc to publish the docs, or are we going to parse/integrate into the main docs like we do with Sphinx?

The plan is to do both.  A lot of go users prefer the output of godoc when they google the package. I don't expect everybody to use our website for that.

> IMO, the suckiness of the tool shouldn't be informing the package structure.

My research indicates that this is actually the Go way -- layout your code to make godoc happy and produce readable results.

**Comment by elprans** [comment]
> A lot of go users prefer the output of godoc when they google the package. 

Can we maybe just stick a hyperlink to our docs or is that frowned upon?

**Comment by 1st1** [comment]
> Can we maybe just stick a hyperlink to our docs or is that frowned upon?

I guess we could, but it seems to me that we'd be going against the grain with that. Maybe breaking out error types into a separate package isn't that bad?

**Comment by fmoor** [comment]
> Can we maybe just stick a hyperlink to our docs or is that frowned upon?

It's not that its frowned upon. Its that `pkg.go.dev/github.com/edgedb/edgedb-go/` is likely to be the top result for may edgedb-go related searches and people are accustomed to looking there for documentation. If the first thing they find there is terrible, its not a great first impression.

**Comment by fmoor** [comment]
Random thought. This has already been discussed more or less but maybe it is worth looking at again. What about implementing the error hierarchy using a method on `edgedb.Error`?

```go
err := pool.Query(...)

var edbErr edgedb.Error
if errors.As(err, &edbErr) && edbErr.Is(edgedb.ConfigureationError) {
    ...
}
```

- This would make it so that there is only one error type. Having tones of error types or interfaces is very uncommon in go.
- There would not be a need to split the edgedb package because the `edgedb.XYZError`s would be constants instead of interfaces so they won't show up in the index. godoc still includes them it just puts them in the section for their type `edgedb.ErrorCategory` or something.

**Comment by 1st1** [comment]
> What about implementing the error hierarchy using a method on edgedb.Error?

Yeah. Maybe we should do that, indeed.

BTW, remind me, what API will we have for letting users access error types properties? E.g. consider I have this error type (using https://github.com/edgedb/edgedb/discussions/1849 proposal):

```
  error type MyError extending errors::Error {
    property app_code -> int64;
  }
```

How would I access the `app_code` property on an `var edbErr edgedb.Error` object?

**Comment by 1st1** [comment]
> In any case, I think this is an orthogonal consideration. There is going to have to be a pattern like this for user defined errors regardless of weather we have 1 error type or many.

Not really. If we end up with a single error type we also need to figure out how we reflect various properties, built-in and user defined. Looking at https://github.com/edgedb/edgedb/discussions/1849, how would I unpack something like `Error.location`, a tuple type, using the `Property(...)` API you suggested? 

(I'm only using `Error.location` as an example here; there will be other complex properties defined on child built-in error types, so they'll have to be accessed via `Property(...)`.)

> Perhaps more relevant, having a single error type with a method like Is(edgedb.ErrorCategory) bool allows the category checking to be extended to user defined types using the same mechanism. The error category type might be type ErrorCategory string and the value could be the fully qualified type name "mymod::UserError3". I'm not sure it would be practical, but it at least seems possible.

Sure, that works.

**Comment by fmoor** [comment]
> how would I unpack something like Error.location, a tuple type, using the Property(...) API you suggested?

Using the 2 return value approach would look something like this:
```go
err := con.Query(...)
var edbErr edgedb.Error
if errors.As(err, &edbErr) {
    location, ok := edbErr.Property("location")
    if ok {
        lineNo := location.([]int64)[0]
    }
}
```

But with known properties we aren't limited to a completely generic method. There can be methods that return a struct when the type implements that field and returns nil otherwise. This would be reminiscent of [the net package's Error type](https://golang.org/pkg/net/#Error). Its also nicer to work with because it doesn't require type assertions everywhere because the return value is typed `Location() *struct{ LineNo int }`.
```go
err := con.Query(...)
var edbErr edgedb.Error
if errors.As(err, &edbErr) {
    location := edbErr.Location()
    if location != nil {
        fmt.Println(location.LineNo)
    }
}
```

**Comment by 1st1** [comment]
@fmoor, as we discussed on the call, let's rewrite the API to follow the design you outlined in https://github.com/edgedb/edgedb-go/issues/64#issuecomment-765014347.
