### ISSUE TITLE
change printed reprisentation of UUID

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#71]
Currently printed UUID struct fields look like `[100 200 103 104 150 160 170 10 80 70 60 50 40 30 20 1]` which is the default way that go prints byte arrays. This is very difficult to match up with the output from the edgedb cli and other clients. It seems like this should be changed to look like the output from every other edgedb client `64c86768-96a0-aa0a-5046-3c32281e1401`.

**Comment by fmoor** [comment]
It looks like go only provides printing/formatting hooks for the object that was printed. These hooks don't seem to be called recursively. If that is true then the only way to make id fields look like other drivers would be to change the type to `type UUID string` and use the formatted string as the value. Not sure this is a great idea.

**Comment by 1st1** [comment]
> Not sure this is a great idea.

What do other drivers do?

**Comment by fmoor** [comment]
> What do other drivers do?

Nothing. They don't provide any go types. I looked at https://github.com/google/uuid and https://github.com/satori/go.uuid and they don't seem to have any magic either. Even standard library types like time.Time and time.Duration get printed in the default format when they are fields. I don't think there is anything you can do about this.

There is functionality to adjust the format when a value is printed directly and not as a field of something else and that is already implemented, but it seems like it would be common to print a struct with an `id` field.

Perhaps we should get some user feedback before deciding something needs to change?

**Comment by 1st1** [comment]
> Perhaps we should get some user feedback before deciding something needs to change?

But changing UUID decode from bytes to str would be a backwards incompatible change.

Is it possible to:

* accept UUID arguments as bytes and receive UUIDs into bytes struct fields

and

* accept UUID arguments as strings & receive UUIDs into str struct fields?

**Comment by fmoor** [comment]
> Is it possible to:
accept UUID arguments as bytes and receive UUIDs into bytes struct fields
and
accept UUID arguments as strings & receive UUIDs into str struct fields?

Yes it is possible. Decoding to `string` is much slower than decoding to `[16]byte` though. 

I'm thinking decoding to strings is not a great idea. All of the most popular UUID libraries use `[16]byte` and people live with printing just the ID when they want it formatted a certain way. They do the same thing for all types including time.Time which is a super common type and very meaningless to humans when printed in the default way.

```go
package main

import (
	"fmt"
	"time"
)

type Thing struct {
	t time.Time
}

func main() {
	t := Thing{time.Now()}

	fmt.Println(t)
	// Output: {{13454110244426743808 1 0x564320}}

	fmt.Printf("%+v\n", t)
	// Output: {t:{wall:13454110244426743808 ext:1 loc:0x567320}}

	fmt.Printf("%#v\n", t)
	// Output: main.Thing{t:time.Time{wall:0xbab699fc00000000, ext:1, loc:(*time.Location)(0x567320)}}

	fmt.Println(t.t)
	// Output: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001
}
```

The more I think about this the more I think doing nothing is the best option.

**Comment by 1st1** [comment]
Well, when you think about this in isolation, then yes, encoding/decoding to strings doesn't make much sense. But what about when you start coding an app, and you need to render UUIDs in HTML, or parse them fro URLs?  How easy would it be to convert to/from text representation of UUIDs to bytes? Do third-party Go UUID packages make that easy?

**Comment by fmoor** [comment]
>  How easy would it be to convert to/from text representation of UUIDs to bytes?

This is already implemented.

```go
uuid := UUID{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}

fmt.Println(uuid)
// output: 00010203-0405-0607-0809-0a0b0c0d0e0f

msg := fmt.Sprintf("your id is %v", uuid)
fmt.Println(msg)
// output: your id is 00010203-0405-0607-0809-0a0b0c0d0e0f
```

When the uuid value is the thing that is printed it is formatted correctly. When you print a data structure that has an id in it it, the id is not formatted nicely. The dynamic is the same as the time.Time example here https://github.com/edgedb/edgedb-go/issues/71#issuecomment-765709559

**Comment by fmoor** [comment]
The edgedb.UUID implementation also plays nice with `encoding/json` too so that json strings are properly formatted and can be encoded/decoded as UUID values.

**Comment by 1st1** [comment]
> The edgedb.UUID implementation also plays nice with encoding/json so that json strings are properly formatted and can be encoded/decoded as UUID values.

Alright, that seals it. Let's keep things as is for now.
