### ISSUE TITLE
prevent ad-hock transactions

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-go#96]
Currently if a connection is acquired either by `ConnectOne()` or `pool.Acquire()` and a transaction is started using `START TRANSACTION` instead of TryTx() or Retry() the connection might reconnect mid transaction.

```go
con.Execute(ctx, "START TRANSACTION")
con.Query(...) // connections fails
con.Query(...) // new connection i.e. different transaction
con.Execute(ctx, "COMMIT")
```

Queries outside of TryTx() or Retry() should not allow explicit transactions.

**Comment by tailhook** [comment]
I would prefer disallowing `START TRANSACTION`, rather than making hacks around transaction state. This is what `ALLOW_CAPABILITIES` is for. Is there any reason somebody needs `START TRANSACTION` instead of `TryTx`?

**Comment by fmoor** [comment]
> I would prefer disallowing START TRANSACTION, rather than making hacks around transaction state.

+1

**Comment by fmoor** [comment]
updated description & title
